### ISSUE TITLE
No output

### ISSUE THREAD

**Issue by hansmestrum** [bachya/lp-vault-manager#10]
Yesterday I upgraded to the new OS X 10.10.2 and now it does not work any more. I did the output trick as mentioned in the other post.
Got this:

File "/Users/hansmestrum/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.1186B027-AB18-4122-8334-243769316500/workflow/workflow.py", line 1971, in run
    func(self)
  File "/Users/hansmestrum/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.1186B027-AB18-4122-8334-243769316500/lpvm.py", line 205, in main
    from LastPassVaultManager import LastPassVaultManager
ImportError: No module named LastPassVaultManager
08:40:48 workflow.py:1996 DEBUG    Workflow finished in 0.062 seconds.

What could be wrong?

**Comment by bachya** [comment]
The telling line:

```
/Users/hansmestrum/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.1186B027-AB18-4122-8334-243769316500/lpvm.py
```

`lpvm.py` is an old file that has been removed since 4.1, I believe. So, it looks like you're using an older version of the workflow (you can determine this by opening the `lpvs` Script Filter and seeing if it mentions `lpvm.py`).

Recommend you update to [the latest release](https://github.com/bachya/lp-vault-manager/releases/tag/v4.2). Going to close this issue; please let me know if you continue to have trouble.

**Comment by hansmestrum** [comment]
I installed the latest version. Did it again.
It did not succeed. i cannot login via lastpass settings in alfred.

Yesterday before updating yosemite it worked!

met vriendelijke groeten 
Hans Mestrum


Op 28 januari 2015 bij 16:26:42, Aaron Bach (notifications@github.com) schreef:

The telling line:

/Users/hansmestrum/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.1186B027-AB18-4122-8334-243769316500/lpvm.py

lpvm.py is an old file that has been removed since 4.1, I believe. So, it looks like you're using an older version of the workflow (you can determine this by opening the lpvs Script Filter and seeing if it mentions lpvm.py).

Recommend you update to the latest release. Going to close this issue; please let me know if you continue to have trouble.

**Comment by hansmestrum** [comment]
Today I tried again but no success. I installed the latest version. Before I updated to the latest update of OS X Yosemite it was running fine. No it has no output.

**Comment by hansmestrum** [comment]
Hi

I replied but did not got an answer.

Up till now I did managed to get it to work.

met vriendelijke groeten 
Hans Mestrum


Op 28 januari 2015 bij 16:26:42, Aaron Bach (notifications@github.com) schreef:

The telling line:

/Users/hansmestrum/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.1186B027-AB18-4122-8334-243769316500/lpvm.py

lpvm.py is an old file that has been removed since 4.1, I believe. So, it looks like you're using an older version of the workflow (you can determine this by opening the lpvs Script Filter and seeing if it mentions lpvm.py).

Recommend you update to the latest release. Going to close this issue; please let me know if you continue to have trouble.

**Comment by bachya** [comment]
As you can see from #3, there is a more systemic issue, but only in certain
accounts. It doesn't occur on my end, unfortunately.

On Mon, Feb 2, 2015 at 8:08 AM, hansmestrum <notifications@github.com>
wrote:

> Hi
>
> I replied but did not got an answer.
>
> Up till now I did managed to get it to work.
>
> met vriendelijke groeten
> Hans Mestrum
>
>
> Op 28 januari 2015 bij 16:26:42, Aaron Bach (notifications@github.com)
> schreef:
>
> The telling line:
>
> /Users/hansmestrum/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.1186B027-AB18-4122-8334-243769316500/lpvm.py
>
>
> lpvm.py is an old file that has been removed since 4.1, I believe. So, it
> looks like you're using an older version of the workflow (you can determine
> this by opening the lpvs Script Filter and seeing if it mentions lpvm.py).
>
> Recommend you update to the latest release. Going to close this issue;
> please let me know if you continue to have trouble.
>
> --
> Reply to this email directly or view it on GitHub.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/bachya/lp-vault-manager/issues/10#issuecomment-72472331>
> .
>



-- 


*Aaron Bachbachya1208@gmail.com <bachya1208@gmail.com>(720) 854-5753*

**Comment by hansmestrum** [comment]
What is the next step or better not use the workflow?

met vriendelijke groeten 
Hans Mestrum


Op 2 februari 2015 bij 17:18:32, Aaron Bach (notifications@github.com) schreef:

As you can see from #3, there is a more systemic issue, but only in certain
accounts. It doesn't occur on my end, unfortunately.

On Mon, Feb 2, 2015 at 8:08 AM, hansmestrum <notifications@github.com>
wrote:

> Hi
>
> I replied but did not got an answer.
>
> Up till now I did managed to get it to work.
>
> met vriendelijke groeten
> Hans Mestrum
>
>
> Op 28 januari 2015 bij 16:26:42, Aaron Bach (notifications@github.com)
> schreef:
>
> The telling line:
>
> /Users/hansmestrum/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.1186B027-AB18-4122-8334-243769316500/lpvm.py
>
>
> lpvm.py is an old file that has been removed since 4.1, I believe. So, it
> looks like you're using an older version of the workflow (you can determine
> this by opening the lpvs Script Filter and seeing if it mentions lpvm.py).
>
> Recommend you update to the latest release. Going to close this issue;
> please let me know if you continue to have trouble.
>
> --
> Reply to this email directly or view it on GitHub.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/bachya/lp-vault-manager/issues/10#issuecomment-72472331>
> .
>



--


*Aaron Bachbachya1208@gmail.com <bachya1208@gmail.com>(720) 854-5753*

**Comment by bachya** [comment]
Feel free to fork the project and dig into the code; I'm doing this in my
spare time, so I may not be able to publish updates (if/when I find
resolutions to the current issues) as quickly.

On Mon, Feb 2, 2015 at 9:37 AM, hansmestrum <notifications@github.com>
wrote:

> What is the next step or better not use the workflow?
>
> met vriendelijke groeten
> Hans Mestrum
>
>
> Op 2 februari 2015 bij 17:18:32, Aaron Bach (notifications@github.com)
> schreef:
>
> As you can see from #3, there is a more systemic issue, but only in
> certain
> accounts. It doesn't occur on my end, unfortunately.
>
> On Mon, Feb 2, 2015 at 8:08 AM, hansmestrum <notifications@github.com>
> wrote:
>
> > Hi
> >
> > I replied but did not got an answer.
> >
> > Up till now I did managed to get it to work.
> >
> > met vriendelijke groeten
> > Hans Mestrum
> >
> >
> > Op 28 januari 2015 bij 16:26:42, Aaron Bach (notifications@github.com)
> > schreef:
> >
> > The telling line:
> >
> >
> /Users/hansmestrum/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.1186B027-AB18-4122-8334-243769316500/lpvm.py
>
> >
> >
> > lpvm.py is an old file that has been removed since 4.1, I believe. So,
> it
> > looks like you're using an older version of the workflow (you can
> determine
> > this by opening the lpvs Script Filter and seeing if it mentions
> lpvm.py).
> >
> > Recommend you update to the latest release. Going to close this issue;
> > please let me know if you continue to have trouble.
> >
> > --
> > Reply to this email directly or view it on GitHub.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/bachya/lp-vault-manager/issues/10#issuecomment-72472331>
>
> > .
> >
>
>
>
> --
>
>
> *Aaron Bachbachya1208@gmail.com <bachya1208@gmail.com>(720) 854-5753*
> --
> Reply to this email directly or view it on GitHub.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/bachya/lp-vault-manager/issues/10#issuecomment-72488619>
> .
>



-- 


*Aaron Bachbachya1208@gmail.com <bachya1208@gmail.com>(720) 854-5753*

**Comment by hansmestrum** [comment]
Ok.

your workflow does not work.

Deleted.

met vriendelijke groeten 
Hans Mestrum


Op 2 februari 2015 bij 18:09:41, Aaron Bach (notifications@github.com) schreef:

Feel free to fork the project and dig into the code; I'm doing this in my
spare time, so I may not be able to publish updates (if/when I find
resolutions to the current issues) as quickly.

On Mon, Feb 2, 2015 at 9:37 AM, hansmestrum <notifications@github.com>
wrote:

> What is the next step or better not use the workflow?
>
> met vriendelijke groeten
> Hans Mestrum
>
>
> Op 2 februari 2015 bij 17:18:32, Aaron Bach (notifications@github.com)
> schreef:
>
> As you can see from #3, there is a more systemic issue, but only in
> certain
> accounts. It doesn't occur on my end, unfortunately.
>
> On Mon, Feb 2, 2015 at 8:08 AM, hansmestrum <notifications@github.com>
> wrote:
>
> > Hi
> >
> > I replied but did not got an answer.
> >
> > Up till now I did managed to get it to work.
> >
> > met vriendelijke groeten
> > Hans Mestrum
> >
> >
> > Op 28 januari 2015 bij 16:26:42, Aaron Bach (notifications@github.com)
> > schreef:
> >
> > The telling line:
> >
> >
> /Users/hansmestrum/Dropbox/alfred/Alfred.alfredpreferences/workflows/user.workflow.1186B027-AB18-4122-8334-243769316500/lpvm.py
>
> >
> >
> > lpvm.py is an old file that has been removed since 4.1, I believe. So,
> it
> > looks like you're using an older version of the workflow (you can
> determine
> > this by opening the lpvs Script Filter and seeing if it mentions
> lpvm.py).
> >
> > Recommend you update to the latest release. Going to close this issue;
> > please let me know if you continue to have trouble.
> >
> > --
> > Reply to this email directly or view it on GitHub.
> >
> > --
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/bachya/lp-vault-manager/issues/10#issuecomment-72472331>
>
> > .
> >
>
>
>
> --
>
>
> *Aaron Bachbachya1208@gmail.com <bachya1208@gmail.com>(720) 854-5753*
> --
> Reply to this email directly or view it on GitHub.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/bachya/lp-vault-manager/issues/10#issuecomment-72488619>
> .
>



--


*Aaron Bachbachya1208@gmail.com <bachya1208@gmail.com>(720) 854-5753*

**Comment by MattKneale** [comment]
@hansmestrum For you. And me. But for many others it does work. Please be more civil...

**Comment by shkm** [comment]
+1 @MattKneale. I currently don't have time to read through recent progress and help with debugging, but the author has clearly spent a lot of time writing what looks like a great workflow. I'm sure it's fantastic when it works :).

**Comment by bachya** [comment]
@MattKneale @shkm Thanks, guys. I appreciate your support. Believe me, it irks me to no end that my workflow works for many, but not for all. I'm still holding out hope that at some point, the silver bullet will appear, but to date, this is been an incredibly difficult problem.

**Comment by bdsivak** [comment]
I'd still love to try to help, @bachya.  I think one of the earlier posters was on to something with the entries that require passwords each time.  Although I don't have any of those, I do notice lpass processes running in the background forever when I execute lpvs from alfred.  Also, interestingly, I can replicate the following steps:

1.  Execute lpsettings lastpass-login
>> nothing happens, lpass process appears in task list.

2.  Kill lpass task
>> alfred window reappears with command ">/usr/local/bin/lpass login xxx@yyy.com && exit" populated

3.  Execute lpsettings lastpass-logout 
>> nothing happens, lpass process appears in task list.

4.  Kill lpass task
>> notification appears that lastpass has been logged out.

I mention this because it's similar behavior that I see (in the task list, at least) when trying to execute the lpvs command.  Just wondering if that makes it easier to debug.
