### ISSUE TITLE
ignore password in Clipboard

### ISSUE THREAD

**Issue by ssolida** [bachya/lp-vault-manager#13]
Hi guys !
Is there a workaround to clear/ignore the password inside Alfred Clipboard ? 
I know that Alfred Clipboard can ignore Apps (with Keychain,Wallet,1Password... as default), but no way to add lastpass-cli :s

**Comment by bachya** [comment]
Hi @ssolida – are you asking whether LastPass passwords can be hidden from Alfred's Clipboard History?

**Comment by ssolida** [comment]
yes, that's exactly what I would like to do....

**Comment by bachya** [comment]
Great idea, but unfortunately, I don't think it's possible; LPVM isn't a "focusable application" in the traditional sense (I'm just running several Python scripts). Sorry!
