### ISSUE TITLE
lpdd fails silently

### ISSUE THREAD

**Issue by unsalted** [bachya/lp-vault-manager#7]
Don't know whats going on with it but lpdd seems to just fail silently

**Comment by bachya** [comment]
Are you logged into LastPass? What happens if, in Terminal, you run `lpass ls`?

**Comment by unsalted** [comment]
Yes I'm logged in, if I run lpass ls it reads out my pass sites.


—

**Comment by fmquaglia** [comment]
@bachya same issue here, and same result of ```lpass ls``` command as @unsalted

**Comment by bachya** [comment]
Thanks, guys – what versions of:

* OS X
* Python

...do you have?

**Comment by fmquaglia** [comment]
@bachya OS X 10.9.5 and python 2.7.8

**Comment by bachya** [comment]
@fmquaglia – I'm running Yosemite, so I'm unfortunately not able to test whether there is some sort of Mavericks issue. Could you try [the 4.2 pre-release](https://github.com/bachya/lp-vault-manager/releases/tag/pre-v4.2) and see if it clears up your issue?

**Comment by fmquaglia** [comment]
@bachya thanks, buddy! 
Unfortunately it didn't work, same result. 
I can't install Yosemite right now because I would break my Dev environment.
If I have any update I'll ping you back.

**Comment by bachya** [comment]
@fmquaglia Take a look at the bottom of [this thread](https://github.com/bachya/lp-vault-manager/issues/3) – try my steps and see if anything different happens. Logs always help!

**Comment by unsalted** [comment]
I’m on Yosemite, and it still happens to me.  I’ll try “whats on the bottom of the thread”, this afternoon when I have time.  Where do I find the logs?


—

**Comment by bachya** [comment]
@unsalted: http://blog.alfredapp.com/2014/03/12/alfred-v2-2-released-workflow-organisation-and-debugging/

**Comment by fmquaglia** [comment]
@bachya 
I'm running the v4.2.0

In the debug log I see messages like this every time I try to execute most of the triggers:

```
Starting debug for 'LastPass Vault Manager'

[ERROR: alfred.workflow.input.scriptfilter] Code 0: 19:33:00 workflow.py:1386 DEBUG    Reading settings from `/Users/fabricio/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
19:33:00 workflow.py:1960 DEBUG    Workflow version : 4.2.0
19:33:00 workflow.py:2221 DEBUG    Update check not due
19:33:00 lpsettings_query.py:35 DEBUG    Query arguments: [u'']
19:33:00 lpsettings_query.py:43 DEBUG    Parsed command: list-settings
19:33:00 lpsettings_query.py:44 DEBUG    Parsed argument: None
19:33:00 lpsettings_query.py:45 DEBUG    Parsed delimiter: >
19:33:00 lpsettings_query.py:46 DEBUG    Parsed query: list-settings
19:33:00 workflow.py:1996 DEBUG    Workflow finished in 0.020 seconds.
```

Is there an issue reading the ```settings.json```?
Any clue?

Thanks!

**Comment by bachya** [comment]
@fmquaglia Run this:

`open ~/Library/Application\ Support/Alfred\ 2/Workflow\ Data/com.bachya.lpvm/settings.json`

And paste the contents of that file. Make note of any weird characters (like "smart" quotes).

**Comment by fmquaglia** [comment]
@bachya here it is:

```json
{
  "__workflow_last_version": "4.2.0", 
  "general": {
    "browser": "1", 
    "cache_bust": 300
  }, 
  "lastpass": {
    "path": "/usr/local/bin/lpass", 
    "username": "matias.quaglia@gmail.com"
  }, 
  "passwords": {
    "avoid_ambiguous": true, 
    "length": 20, 
    "number": 10, 
    "use_digits": true, 
    "use_lowercase": true, 
    "use_symbols": true, 
    "use_uppercase": true
  }
}
```

I don't se anything suspicious. :-/

**Comment by bachya** [comment]
@fmquaglia That all looks correct – so, we know it's not a configuration issue. I'm thinking this is similar to #3, so I'm going to close this and refer you to that thread.
