### ISSUE TITLE
lpvs not finding anything

### ISSUE THREAD

**Issue by gruntfutuk** [bachya/lp-vault-manager#8]
Hi Aaron,

Whilst relatively new to Alfred and workflows, I am a long term fan of Lastpass, but am attempting to use the command line interface version for the first time. I am sure your workflow is going to be hugely helpful to me, once I figure out what I have done wrong below.

I used the homebrew installation routine for lastpass. Installed your workflow in the usual way.

However, the search does not seem to work. It either just reports searching, with no result or it quickly tells me nothing has been found.

Following guidance given on another issue, I attempted to run lastpass in a terminal. See below. The key issue seems to be: ImportError: No module named LastPassVaultManager. Would appreciate any guidance you can give.

OSX:usr auser$ python /Users/auser/Library/Application\ Support/Alfred\ 2/Alfred.alfredpreferences/workflows/user.workflow.F3FDC3FF-8A3E-4B15-9276-4A1BB2F4AB6A/lpvm.py search-vault "amazon"
13:06:30 workflow.py:1386 DEBUG    Reading settings from `/Users/auser/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
13:06:30 workflow.py:1960 DEBUG    Workflow version : 3.9.0
13:06:30 workflow.py:1978 ERROR    No module named LastPassVaultManager
Traceback (most recent call last):
  File "/Users/auser/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.F3FDC3FF-8A3E-4B15-9276-4A1BB2F4AB6A/workflow/workflow.py", line 1971, in run
    func(self)
  File "/Users/auser/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.F3FDC3FF-8A3E-4B15-9276-4A1BB2F4AB6A/lpvm.py", line 205, in main
    from LastPassVaultManager import LastPassVaultManager
ImportError: No module named LastPassVaultManager
13:06:30 workflow.py:1996 DEBUG    Workflow finished in 0.036 seconds.
OSX:usr auser$

**Comment by bachya** [comment]
HI @gruntfutuk – could you tell me what version of:

* OS X
* Python

...you have?

**Comment by bachya** [comment]
@gruntfutuk If 4.2 pre-release doesn't help, I think this falls in line with #3, so I'm going to close this and refer you there.

**Comment by gruntfutuk** [comment]
Just tried the 4.2 pre-release, but I do not get prompted for the login anymore (no terminal window opens when I hit return in lpsettings | modify lastpass settings | Login To LastPass) - ie Alfred command line reads: lpsettings lastpass-login but pressing return does nothing.
