### ISSUE TITLE
LPVS Fails

### ISSUE THREAD

**Issue by markerx** [bachya/lp-vault-manager#9]
First of all, thanks for putting this together. It is a great idea.

Unfortunately, I am having difficulty getting it to play nice, and can get the search feature to work.

Here is the error I am getting in the debug console in Alfred:

[ERROR: alfred.workflow.input.scriptfilter] Code 0: 08:28:52 workflow.py:1386 DEBUG    Reading settings from `/Users/Brandon/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
08:28:52 workflow.py:1960 DEBUG    Workflow version : 4.2.0
08:28:52 lpvs_query.py:30 DEBUG    Query arguments: [u'search-vault-for-query', u'a']
08:28:52 lpvs_query.py:38 DEBUG    Parsed command: search-vault-for-query
08:28:52 lpvs_query.py:39 DEBUG    Parsed argument: a
08:28:52 lpvs_query.py:40 DEBUG    Parsed delimiter: >
08:28:52 lpvs_query.py:41 DEBUG    Parsed query: search-vault-for-query a
08:28:52 lpvs_query.py:53 DEBUG    Executing command: search-vault-for-query
08:28:52 background.py:180 DEBUG    Command arguments cached to `/Users/Brandon/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.bachya.lpvm/update.argcache`
08:28:52 background.py:184 DEBUG    Calling [u'/usr/bin/python', '/Users/Brandon/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.EAFF1D69-B788-407C-8B7A-6DD63E81C1C5/workflow/background.pyc', u'update'] ...
08:28:52 workflow.py:1960 DEBUG    Workflow version : 4.2.0
08:28:52 workflow.py:1996 DEBUG    Workflow finished in 0.017 seconds.
08:28:52 workflow.py:1996 DEBUG    Workflow finished in 0.018 seconds.
08:28:53 background.py:189 DEBUG    Executing task `update` in background...
08:28:53 utilities.py:221 DEBUG    Search results: None
08:28:53 workflow.py:1996 DEBUG    Workflow finished in 0.098 seconds.
[ERROR: alfred.workflow.input.scriptfilter] Code 0: 08:28:53 workflow.py:1386 DEBUG    Reading settings from `/Users/Brandon/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
08:28:53 workflow.py:1960 DEBUG    Workflow version : 4.2.0
08:28:53 lpvs_query.py:30 DEBUG    Query arguments: [u'search-vault-for-query', u'ama']
08:28:53 lpvs_query.py:38 DEBUG    Parsed command: search-vault-for-query
08:28:53 lpvs_query.py:39 DEBUG    Parsed argument: ama
08:28:53 lpvs_query.py:40 DEBUG    Parsed delimiter: >
08:28:53 lpvs_query.py:41 DEBUG    Parsed query: search-vault-for-query ama
08:28:53 lpvs_query.py:53 DEBUG    Executing command: search-vault-for-query
08:28:53 background.py:180 DEBUG    Command arguments cached to `/Users/Brandon/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.bachya.lpvm/update.argcache`
08:28:53 background.py:184 DEBUG    Calling [u'/usr/bin/python', '/Users/Brandon/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.EAFF1D69-B788-407C-8B7A-6DD63E81C1C5/workflow/background.pyc', u'update'] ...
08:28:53 workflow.py:1960 DEBUG    Workflow version : 4.2.0
08:28:53 workflow.py:1996 DEBUG    Workflow finished in 0.020 seconds.
08:28:53 workflow.py:1996 DEBUG    Workflow finished in 0.021 seconds.
08:28:53 background.py:189 DEBUG    Executing task `update` in background...
08:28:53 utilities.py:221 DEBUG    Search results: None
08:28:53 workflow.py:1996 DEBUG    Workflow finished in 0.101 seconds.
[ERROR: alfred.workflow.input.scriptfilter] Code 0: 08:28:53 workflow.py:1386 DEBUG    Reading settings from `/Users/Brandon/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
08:28:53 workflow.py:1960 DEBUG    Workflow version : 4.2.0
08:28:53 lpvs_query.py:30 DEBUG    Query arguments: [u'search-vault-for-query', u'amaz']
08:28:53 lpvs_query.py:38 DEBUG    Parsed command: search-vault-for-query
08:28:53 lpvs_query.py:39 DEBUG    Parsed argument: amaz
08:28:53 lpvs_query.py:40 DEBUG    Parsed delimiter: >
08:28:53 lpvs_query.py:41 DEBUG    Parsed query: search-vault-for-query amaz
08:28:53 lpvs_query.py:53 DEBUG    Executing command: search-vault-for-query
08:28:53 background.py:180 DEBUG    Command arguments cached to `/Users/Brandon/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.bachya.lpvm/update.argcache`
08:28:53 background.py:184 DEBUG    Calling [u'/usr/bin/python', '/Users/Brandon/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.EAFF1D69-B788-407C-8B7A-6DD63E81C1C5/workflow/background.pyc', u'update'] ...
08:28:53 workflow.py:1960 DEBUG    Workflow version : 4.2.0
08:28:53 workflow.py:1996 DEBUG    Workflow finished in 0.016 seconds.
08:28:53 workflow.py:1996 DEBUG    Workflow finished in 0.017 seconds.
08:28:53 background.py:189 DEBUG    Executing task `update` in background...
08:28:53 utilities.py:221 DEBUG    Search results: None
08:28:53 workflow.py:1996 DEBUG    Workflow finished in 0.099 seconds.
[ERROR: alfred.workflow.input.scriptfilter] Code 0: 08:28:53 workflow.py:1386 DEBUG    Reading settings from `/Users/Brandon/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
08:28:53 workflow.py:1960 DEBUG    Workflow version : 4.2.0
08:28:53 lpvs_query.py:30 DEBUG    Query arguments: [u'search-vault-for-query', u'amazo']
08:28:53 lpvs_query.py:38 DEBUG    Parsed command: search-vault-for-query
08:28:53 lpvs_query.py:39 DEBUG    Parsed argument: amazo
08:28:53 lpvs_query.py:40 DEBUG    Parsed delimiter: >
08:28:53 lpvs_query.py:41 DEBUG    Parsed query: search-vault-for-query amazo
08:28:53 lpvs_query.py:53 DEBUG    Executing command: search-vault-for-query
08:28:53 background.py:180 DEBUG    Command arguments cached to `/Users/Brandon/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.bachya.lpvm/update.argcache`
08:28:53 background.py:184 DEBUG    Calling [u'/usr/bin/python', '/Users/Brandon/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.EAFF1D69-B788-407C-8B7A-6DD63E81C1C5/workflow/background.pyc', u'update'] ...
08:28:53 workflow.py:1960 DEBUG    Workflow version : 4.2.0
08:28:53 workflow.py:1996 DEBUG    Workflow finished in 0.017 seconds.
08:28:53 workflow.py:1996 DEBUG    Workflow finished in 0.018 seconds.
08:28:53 background.py:189 DEBUG    Executing task `update` in background...
08:28:53 utilities.py:221 DEBUG    Search results: None
08:28:53 workflow.py:1996 DEBUG    Workflow finished in 0.091 seconds.
[ERROR: alfred.workflow.input.scriptfilter] Code 0: 08:28:54 workflow.py:1386 DEBUG    Reading settings from `/Users/Brandon/Library/Application Support/Alfred 2/Workflow Data/com.bachya.lpvm/settings.json` ...
08:28:54 workflow.py:1960 DEBUG    Workflow version : 4.2.0
08:28:54 lpvs_query.py:30 DEBUG    Query arguments: [u'search-vault-for-query', u'amazon']
08:28:54 lpvs_query.py:38 DEBUG    Parsed command: search-vault-for-query
08:28:54 lpvs_query.py:39 DEBUG    Parsed argument: amazon
08:28:54 lpvs_query.py:40 DEBUG    Parsed delimiter: >
08:28:54 lpvs_query.py:41 DEBUG    Parsed query: search-vault-for-query amazon
08:28:54 lpvs_query.py:53 DEBUG    Executing command: search-vault-for-query
08:28:54 background.py:180 DEBUG    Command arguments cached to `/Users/Brandon/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/com.bachya.lpvm/update.argcache`
08:28:54 background.py:184 DEBUG    Calling [u'/usr/bin/python', '/Users/Brandon/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.EAFF1D69-B788-407C-8B7A-6DD63E81C1C5/workflow/background.pyc', u'update'] ...
08:28:54 workflow.py:1960 DEBUG    Workflow version : 4.2.0
08:28:54 workflow.py:1996 DEBUG    Workflow finished in 0.020 seconds.
08:28:54 workflow.py:1996 DEBUG    Workflow finished in 0.021 seconds.
08:28:54 background.py:189 DEBUG    Executing task `update` in background...
08:28:54 utilities.py:221 DEBUG    Search results: None
08:28:54 workflow.py:1996 DEBUG    Workflow finished in 0.106 seconds.

Any Ideas?

Thanks in advance!

**Comment by learn2reid** [comment]
I'm having the same issue!
Really want to use this plugin :-(

**Comment by bachya** [comment]
Take a look at #3; does that describe the issue you're having?
